access_token = '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'
owner = 'bpechetti'
repo = 'CICD_Pipeline'
branch ='main' 
local_repo = 'D:\herovired\CICD\CICD_Pipeline'
nginx_path ='/var/www/html/CICD_Pipeline'
files_to_copy ='index.html'