access_token = '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'
owner = 'bpechetti'
repo = 'CICD_Pipeline'
branch ='main' 
local_repo = 'D:\herovired\CICD\CICD_Pipeline'
nginx_path ='/var/www/html/CICD_Pipeline'
files_to_copy ='index.html'