access_token = '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'
owner = 'bpechetti'
repo = 'CICD_Pipeline'
branch ='main' 
local_repo = 'D:\herovired\CICD\CICD_Pipeline'
nginx_path ='/var/www/html/CICD_Pipeline'
files_to_copy ='index.html'